name: Get BQ Result
on: [push]
#workflow_dispatch
jobs:
  get-secret:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Use gcloud CLI'
        run: 'gcloud auth login'
        # service-account-1@my-project.iam.gserviceaccount.com
      # Configure Workload Identity Federation via a credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          #token_format: 'access_token'
          workload_identity_provider: 'projects/737712162241/locations/global/workloadIdentityPools/github-pool-xn/providers/github-provider'
          service_account: 'bq-685@sawyer-work-1804.iam.gserviceaccount.com'
      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      # Now you can run gcloud commands authenticated as the impersonated service account.
      - id: 'gcloud'
        name: 'Query Result from example_team Table'
        # run: "gcloud storage ls"
        run: |-
          bq query --nouse_legacy_sql 'SELECT * FROM `sawyer-work-1804`.SAWYER_WILLING.example_teams LIMIT 1000'

#https://iam.googleapis.com/projects/737712162241/locations/global/workloadIdentityPools/githubactions/providers/github
#gcloud iam workload-identity-pools describe "githubactions" --project="${PROJECT_ID}" --location="global" --format="value(name)"