name: Check GCS Bucket
on: [push]
jobs:
  List-Buckets:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: 'projects/737712162241/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider'
          service_account: 'gh-runner@sawyer-work-1804.iam.gserviceaccount.com'
          token_format: 'access_token'
          access_token_lifetime: '300s'
          
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Check GCS Bucket"
        run: "gcloud storage ls"
      