name: Check GCS Bucket
on: [push]
jobs:
  List-Buckets:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v3"
        with:
          workload_identity_provider: 'projects/737712162241/locations/global/workloadIdentityPools/github-pool-tf1/providers/github-provider'
          service_account: 'bq-685@sawyer-work-1804.iam.gserviceaccount.com'

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Check GCS Bucket"
        run: "gcloud storage ls"