name: GCP1
on: [push]
jobs:
  List-Buckets:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v2"

      - id: google_cloud_auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: projects/${{ secrets.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_IDENTITY_POOL }}/providers/${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.WORKLOAD_IDENTITY_SA }}


      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          CLOUDSDK_AUTH_ACCESS_TOKEN: ${{ steps.google_cloud_auth.outputs.access_token }}
        with:
          args: info